services:
  whiteboard:
    image: marvinalegre/whiteboard:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whiteboard.rule=Host(`whiteboard.testingg.bid`)"
      - "traefik.http.routers.whiteboard.entrypoints=websecure"
      - "traefik.http.routers.whiteboard.tls.certresolver=myresolver"
      - "traefik.http.services.whiteboard.loadbalancer.server.port=4001"
    networks:
      - web-traffic

networks:
  web-traffic:
    external: true
